spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:30436/railway
    username: root
    password: pYBXUeXdagsgjgcZYScRMpkzYDbhyLLx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}
